### ISSUE TITLE
Refiner blueprints

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#249]
This is a mega-issue tracking all the planned changes to the refiner. @jonsterling Feel free to change the list directly.

- [x] Avoid direct use of `makeGoal` in most rules. To be finished by #247.
- [x] Revamp the machine! #207 #230.
- [x] Assertions and substitutions. #255 #259.
- [ ] Separation of tactics and rules. #245.
    - [ ] Move `AutoEq` out of individual modules. (Partially done.)
- [ ] Twin realizers? #208 
- [ ] `HCom.True`, `Coe.True` and `Com.True` etc. #184.
- [ ] Unification with the machine? #25.
- [ ] Better programming style for rules that do not use `alpha`.

**Comment by jonsterling** [comment]
sounds good! Let me suggest that things like improving the programming style for rules that do not use `alpha` should be considered a very low priority. I want to continue to make progress on the important things we really need to do (either replacing the machine, or implementing further rules, or fixing bugs) and would like to avoid getting stuck in a yak-shaving mode.

**Comment by favonia** [comment]
This meta-issue is completely useless.
